name: Publish Module

on:
  push:
    tags:
      - 1.*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish Module to PowerShell Gallery
        shell: pwsh
        run: |
          $ModulePSD1 = Get-ChildItem -Recurse *.psd1
          $ModulePSD1 |
          ForEach-Object {
            Test-ModuleManifest $_.FullName

            $ModulePath = Split-Path -Parent $_.FullName
            $ModuleName = $_.BaseName
            Write-Host "Publishing module $ModuleName"
            Publish-Module -Path $ModulePath -NuGetApiKey '${{ secrets.PS_GALLERY_KEY }}' -Verbose
          }